version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fcjbookstore"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eu65yptq2x69"
s3_prefix = "fcjbookstore"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BookStoreWebName=\"fcj-book-store-2023\" S3ImageStoreName=\"book-image-store-2023\" S3ImageResizedName=\"book-image-resize-store-2023\" AdminEmail=\"khavan.work@gmail.com\""
image_repositories = []
